# Generated by Django 6.0.4 on 2026-05-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('OPERADOR_DEPOSITO', 'Operador de deposito'), ('ENCARGADO_DEPOSITO', 'Encargado de deposito'), ('REPOSITOR', 'Repositor'), ('ENCARGADO_SALON', 'Encargado de salón'), ('ENCARGADO_CAJA', 'Encargado de caja'), ('RESPONSABLE_ABASTECIMIENTO', 'Responsable de abastecimiento'), ('ADMINISTRADOR_SISTEMA', 'Administrador del sistema')], max_length=50, unique=True),
        ),
    ]
